name: dev
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel=6.4.*
  - ipython=7.29.*
  - matplotlib=3.5.*
  - pandas=1.2.*
  - papermill=2.3.*
  - python=3.9
  - pytest=6.2.*
  - psycopg2=2.8.*
  - sqlalchemy=1.4.*
  - requests=2.25.*
  