version: '3'
services:
  ml:
    container_name: ml
    image: ml-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mnt/app
    environment:
      - PORT=8888
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "8888:8888"